# GitHub Actions工作流配置文件

name: Build and Release

on:
  push:
    tags:
      - "v*.*.*" # 当推送符合模式v*.*.*的标签时触发工作流
  workflow_dispatch:

permissions:
  contents: write # 允许写入仓库内容

jobs:
  release:
    name: Release on ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          [
            macos-x86_64,
            macos-arm64,
            linux-x86_64-musl,
            linux-arm64-musl,
            windows-x86_64,
            windows-arm64,
          ]
        include:
          - platform: macos-x86_64
            target: x86_64-apple-darwin
            os: macos-latest
            bin: ntpclient

          - platform: macos-arm64
            target: aarch64-apple-darwin
            os: macos-latest
            bin: ntpclient

          - platform: linux-x86_64-musl
            target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            bin: ntpclient

          - platform: linux-arm64-musl
            target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            bin: ntpclient

          - platform: windows-x86_64
            target: x86_64-pc-windows-msvc
            os: windows-latest
            bin: ntpclient.exe

          - platform: windows-arm64
            target: aarch64-pc-windows-msvc
            os: windows-latest
            bin: ntpclient.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fix revision count

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.target }}-main
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: install frontend dependencies
        run: yarn install # change this to npm, pnpm or bun depending on which one you use.
      - name: install bun
        run: yarn add bun -g

      - name: Build debug binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "bun tauri build"
          target: ${{ matrix.target }}
          strip: true

      - name: Prepare assets
        shell: bash
        run: |
          tar -cvzf ${{ matrix.target }}.tar.gz \
            src-tauri/target/bundle

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          rev_count=$(git rev-list --count HEAD)
          echo rev_count=${rev_count} >> $GITHUB_OUTPUT

      - name: Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.target }}.tar.gz
          tag_name: r${{ steps.vars.outputs.rev_count }}
          prerelease: false
          make_latest: true
